fix: refactor test for clarinet 2.0
hirosystems/clarity-examples pull request #19
Opened 2023-11-10 12:21 UTC by beguene

update zip script to ignore node_mdules/
update metada.json

closes https://github.com/hirosystems/platform/issues/787

2023-11-10 13:23 UTC, hugocaillard requested changes
A few remarks.

I didn't comment every line but in general:
- I think the console.log can be removed everywhere
- Privilege custom clarity matchers as much as possible
- No need to await `simnet.callPublicFunction` or `simnet.mineBlock`
- `.callPublicFunction` can often be used instead of `mineBlock` (if there's only when transaction in the block)


Each example should have a tsonfig.json as well:
```
{
  "compilerOptions": {
    "target": "ESNext",
    "useDefineForClassFields": true,
    "module": "ESNext",
    "lib": ["ESNext"],
    "skipLibCheck": true,

    "moduleResolution": "bundler",
    "allowImportingTsExtensions": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,

    "strict": true,
    "noImplicitAny": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noFallthroughCasesInSwitch": true
  },
  "include": ["node_modules/@hirosystems/clarinet-sdk/vitest-helpers/src", "tests"]
}
```


Thanks @beguene!

2023-11-10 13:23 UTC, hugocaillard commented on examples/clarity-bitcoin/tests/clarity-bitcoin.test.ts
> +import { Cl, cvToJSON, deserializeCV } from "@stacks/transactions";
```suggestion
import { Cl, ClarityType } from "@stacks/transactions";
```

2023-11-10 13:23 UTC, hugocaillard commented on examples/counter/tests/counter.test.ts
> +    expect(countResponse.result).toStrictEqual(Cl.uint(0));
```suggestion
    expect(countResponse.result).toBeUint(0);
```

2023-11-10 13:23 UTC, hugocaillard commented on examples/clarity-bitcoin/tests/clarity-bitcoin.test.ts
> +    expect(jsonResult.success).toBe(true);
```suggestion
    const { result } =  simnet.callReadOnlyFn(
      contractName,
      "parse-tx",
      [Cl.buffer(Buffer.from(btcTx.slice(2), "hex"))],
      deployer
    );

    expect(result).toHaveClarityType(ClarityType.ResponseOk)
```

Except if you did `cvToJSON` for particular reason, I would favor showcasing clarity custom matchers as much as possible

2023-11-10 13:23 UTC, hugocaillard commented on examples/counter/tests/counter.test.ts
> +    expect(updatedCountResponse.result).toStrictEqual(Cl.uint(2));
```suggestion
    expect(updatedCountResponse.result).toBeUint(2);
```

2023-11-10 13:23 UTC, hugocaillard commented on examples/counter/tests/counter.test.ts
> +    expect(updatedCountResponse.result).toStrictEqual(Cl.uint(1));
```suggestion
    expect(updatedCountResponse.result).toBeUint(1);
```

2023-11-10 13:23 UTC, hugocaillard commented on examples/lightning-swaps/tests/stxswap_v10.test.ts
> +  it("ensures that user can lock and claim stx", async () => {
```suggestion
  it("ensures that user can lock and claim stx" () => {
```

2023-11-10 13:23 UTC, hugocaillard commented on examples/lightning-swaps/tests/stxswap_v10.test.ts
> +  it("ensures that user can lock and claim stx", async () => {
Most of the simnet method are sync. (`mineBlock`, `callPublicFunction`)

2023-11-10 13:23 UTC, hugocaillard commented on examples/lightning-swaps/tests/stxswap_v10.test.ts
> +    ]);
This fine, but we can also prefer `simnet.callPublicFunction` when there's only 1 transaction in the block.

The await can be removed

2023-11-10 13:23 UTC, hugocaillard commented on examples/non-fungible-token/tests/non-fungible-token.test.ts
> +    ]);
Could be `simnet.callPublicFunction`

2023-11-10 14:46 UTC, beguene commented
Thanks a lot @hugocaillard for the review ! 
Regarding the migration, I prefer the new syntax obviously, it's much cleaner, and easier. Love the `simnet` to simulate everything, it's intuitive. Regarding migrating from the old way, it is sometimes easier to start from scratch actually.
Also `Cl.TypeX` is better than TypeXCV.

(the console.log was for debugging, I will remove them)

2023-11-14 13:44 UTC, hugocaillard requested changes
just a couple of remaining logs

2023-11-14 13:44 UTC, hugocaillard commented on examples/counter/tests/counter.test.ts
> +    console.log("countResponse", countResponse);
```suggestion

```

2023-11-14 13:44 UTC, hugocaillard commented on examples/counter/tests/counter.test.ts
> +    console.log("incrementResponse", incrementResponse);
```suggestion
```

2023-11-14 13:44 UTC, hugocaillard commented on examples/lightning-swaps/contracts/stxswap_v10.clar
> +
```suggestion
```

2023-11-14 15:41 UTC, beguene commented
Thanks a lot @hugocaillard !

2023-11-14 16:14 UTC, hugocaillard approved these changes
LGTM

2023-11-29 16:24 UTC, merged