Add README and polish the examples
hirosystems/clarity-examples pull request #9
Opened 2023-03-11 16:35 UTC by sabbyanandan

This proposal includes the following changes:
+ Add README to examples
+ Add a root README with pointers to individual examples along with its purpose, and how to use the examples
+ Update/polish `metadata.json`
+ Reorder examples in `metadata.json`
+ Remove citycoin examples (fixes https://github.com/hirosystems/artemis/issues/253)

2023-03-11 17:06 UTC, hugocaillard requested changes
Thanks @sabbyanandan!

The metadata.json is generated automatically (by running `node scripts/generate-metadata.js` so it shoudln't be edited manually.

If you want to edit the descriptions, this can be done in the `Clarinet.toml` files of each example (then run `node scripts/generate-metadata.js` to update the metadata.json file).

I'll see what can be done regarding the ordering of the project in this file if it matters 👍

2023-03-11 19:43 UTC, sabbyanandan commented
Thanks for the education, @hugocaillard! 

> If you want to edit the descriptions, this can be done in the Clarinet.toml files of each example (then run node scripts/generate-metadata.js to update the metadata.json file).

I pushed another commit with the desired changes to the TOML files; however, I cannot generate the JSON locally. I am on `clarinet-cli` with 1.4.2, but the script fails on my end with the following.

```
╭─sabbyanandan ~/hiro/clarity-examples ‹ruby-2.7.6› ‹add-readmes●›
╰─$ node scripts/generate-metadata.js
/Users/sabbyanandan/hiro/clarity-examples/scripts/generate-metadata.js:22
  if (matches.length === 0) {
              ^

TypeError: Cannot read properties of null (reading 'length')
    at /Users/sabbyanandan/hiro/clarity-examples/scripts/generate-metadata.js:22:15
    at exithandler (node:child_process:427:5)
    at ChildProcess.errorhandler (node:child_process:439:5)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

```

From what I can tell, the `const matches = clarinetVersionOutput.match(/\d+\.\d+\.\d+/);` resolves to `null` on my terminal session. Likely, the OS commands are only partially settling on my end, maybe. I am on a zsh wrapper (with node at `v18.15.0`). 

Either way, the requested changes are submitted except the `metadata.json`. You can do the generate part on your end when reviewing/merging.

Lastly, I would love to order the examples in Artemis like I have them ordered in the root README. If you can make that happen, I owe you a few 🍻 .

2023-03-13 15:19 UTC, leahjlou commented on examples/clarity-bitcoin/README.md
> +## Know your Contract
IMO, all other READMEs should include a similar section as the "blank contract" on how to add new contracts. These are just starters but devs will most likely want to add additional contracts to their projects

2023-03-13 15:23 UTC, leahjlou commented on metadata.json
> +      "title": "hello-world",
The order of this file doesn't matter right now, it's automatically generated. Did you reorder it with the intent that the order would change in the platform app? I think if there is a desired order we should implement that in the Platform app rather than here.

2023-03-13 15:24 UTC, leahjlou commented on metadata.json
> +      "description": "Demonstartes a minimalistic NFT marketplace that allows users to list NFT for sale.",
Typo: "demonstartes" should be "demonstrates"

2023-03-13 15:24 UTC, leahjlou commented on metadata.json
> +      "description": "Demonstrates a trustless atomic swaps between Ordinals and Stacks (STX).",
Grammar seems off here - I'm thinking it should be "Demonstrates a trustless atomic swap" or "Demonstrates trustless atomic swaps"

2023-03-13 15:25 UTC, leahjlou commented on README.md
> +|[nft-marketplace](/examples/nft-marketplace/)          | Demonstartes a minimalistic NFT marketplace that allows users to list NFT for sale |
Same typo here in description

2023-03-13 15:26 UTC, leahjlou commented on examples/blank-project/Clarinet.toml
> +description = "A blank project confirms to Clarinet-compliant project structure"
Should this be "conforms" instead of "confirms"

2023-03-13 15:26 UTC, leahjlou commented on examples/blank-project/README.md
> +This blank project confirms to [Clarinet-compliant](https://docs.hiro.so/clarinet/how-to-guides/how-to-create-new-project) project structure.
Same - should be "conforms"

2023-03-13 15:29 UTC, leahjlou commented on metadata.json
> +      "title": "hello-world",
Feel free to create an issue in the platform app with the order that we want

2023-03-13 15:51 UTC, sabbyanandan commented on examples/blank-project/README.md
> ++ Navigate to `/contracts` folder and create your Clarity contracts
The line-item after this bullet address that, but to make it more clearer, I merged that bit with this bullet.

2023-03-13 15:52 UTC, sabbyanandan commented on examples/blank-project/README.md
> ++ You can manually test your your contracts in the [Clarinet console](https://docs.hiro.so/clarinet/how-to-guides/how-to-test-contract#load-contracts-in-a-console).
Hmm, I had thought about it. Given this is a standalone repo with examples, it would be odd to put such a detail, so I didn't. But anyway, now I have a special NOTE about it.

2023-03-13 15:58 UTC, sabbyanandan commented on metadata.json
> +      "title": "hello-world",
Fair enough re: ordering inside Artemis.

2023-03-13 17:28 UTC, leahjlou commented
Regarding the metadata generation script, the error you're seeing is because of where you're running the script from. This really needs to be improved with clear instructions for how to run the scripts and possibly even automating it. I will create an issue in this repo.

To ensure the zip archives are updated with these changes, can you run `./scripts/create-zips.sh` in the terminal? I am happy to do this for you and push it up to your branch, let me know

2023-03-13 17:30 UTC, leahjlou commented on examples/blank-project/README.md
> ++ Navigate to `/contracts` folder and create your Clarity contracts
Are you referring to the reference to the docs? I'm still worried it might be confusing, because no "navigation" to the `contracts` directory needs to happen at all -- `clarinet contract new` needs to be run at the root of the project. My guess is that most devs will probably try to figure it out without clicking the docs link.

2023-03-13 17:57 UTC, sabbyanandan commented
> Regarding the metadata generation script, the error you're seeing is because of where you're running the script from. This really needs to be improved with clear instructions for how to run the scripts and possibly even automating it. I will create an issue in this repo.

Ah, from `scripts/`, I could generate the file now. Maybe that is what you're referring to. Anyway, all generated files are now in the proposal.

2023-03-13 18:16 UTC, leahjlou commented on scripts/metadata.json
> +{
This file should be moved to the root level of the project. We will improve the scripts/instructions and possibly automate this in [this task](https://github.com/hirosystems/clarity-examples/issues/10)

2023-03-13 18:28 UTC, sabbyanandan commented on examples/blank-project/README.md
> ++ Navigate to `/contracts` folder and create your Clarity contracts
Sorry, missed this. Addressed now.

2023-03-13 19:05 UTC, leahjlou approved these changes
Looks great, thanks!

2023-03-14 11:00 UTC, hugocaillard approved these changes
LGTM!

2023-03-14 11:01 UTC, merged